testing with new configuration

diff --git a/.github/workflows/lighthouse-ci.yml b/.github/workflows/lighthouse-ci.yml
--- a/.github/workflows/lighthouse-ci.yml
+++ b/.github/workflows/lighthouse-ci.yml
@@ -22,10 +22,19 @@ jobs:
               run: yarn build
             - name: Build urls
               run: node ./lighthouse/lighthouse-get-urls.js
-            - name: Run Lighthouse CI
+            - name: Run LHCI (collect, assert, conditional upload)
               run: |
-                  npm install -g @lhci/cli@0.14.x
-                  lhci autorun --config=./lighthouse/lighthouserc.skipAriaAllowed.js --upload.githubStatusCheck=failure-only
-                  lhci autorun --config=./lighthouse/lighthouserc.js --upload.githubStatusCheck=failure-only
+                  lhci collect --config=${{ matrix.config }}
+                  if ! lhci assert --config=${{ matrix.config }}; then
+                  echo "Assertions failed"
+                  lhci upload --config=${{ matrix.config }}
+                  else
+                  echo "Assertions passed, skipping upload."
+                  fi
               env:
                   LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+              strategy:
+                  matrix:
+                      config:
+                          - ./lighthouse/lighthouserc.skipAriaAllowed.js
+                          - ./lighthouse/lighthouserc.js
